In [10]:
import pandas as pd
import numpy as np
from functools import reduce
from datetime import timezone, datetime,date
import pytz

pac = pytz.timezone('America/Los_Angeles')
utc = pytz.timezone('UTC')

In [11]:
def Kel_To_Far(k):
    #c = k + 273
    #f = ((9 * c) / 5) + 32
    f = 1.8*(k - 273) + 32
    return f

In [12]:
path = './Data/historical-hourly-weather-data/temperature.csv'
temp = pd.read_csv(path,index_col='datetime',parse_dates = [0])
Drop_col = [col for col in temp.columns if 'Seattle' not in col]
temp.drop(Drop_col,axis=1,inplace=True)
temp.rename(columns={'Seattle': 'Temp_k'},inplace=True)
temp['Temp_F'] = temp.apply(Kel_To_Far)
#temp.sample(15)

In [13]:
path = './Data/historical-hourly-weather-data/weather_description.csv'
weather_cond = pd.read_csv(path,index_col='datetime',parse_dates = [0])
Drop_col = [col for col in weather_cond.columns if 'Seattle' not in col]
weather_cond.drop(Drop_col,axis=1,inplace=True)
weather_cond.rename(columns={'Seattle': 'weather_cond'},inplace=True)
#weather_cond.sample(15)

In [14]:
path = './Data/historical-hourly-weather-data/pressure.csv'
pressure = pd.read_csv(path,index_col='datetime',parse_dates = [0])
Drop_col = [col for col in pressure.columns if 'Seattle' not in col]
pressure.drop(Drop_col,axis=1,inplace=True)
pressure.rename(columns={'Seattle': 'pressure'},inplace=True)
#pressure.sample(15)
#pressure.index.dtype

In [15]:
path = './Data/historical-hourly-weather-data/wind_speed.csv'
wind = pd.read_csv(path,index_col='datetime',parse_dates = [0])
Drop_col = [col for col in wind.columns if 'Seattle' not in col]
wind.drop(Drop_col,axis=1,inplace=True)
wind.rename(columns={'Seattle': 'wind_speed'},inplace=True)
#wind.sample(15)

In [16]:
dfs = (temp,weather_cond,pressure,wind)
WX = reduce(lambda left,right: pd.merge(left,right,on = 'datetime'),dfs)


#localize as UTC then convert to Pacific
WX = WX.tz_localize(utc,ambiguous = True, nonexistent = 'shift_forward').tz_convert(pac)

WX.drop('Temp_k',axis=1,inplace=True)

WX.sort_index(inplace = True,ascending=False)

WX.index.names=['Date_Join']

#WX = pd.get_dummies(data=WX, columns = ['weather_cond'])
#WX.sample(10)

In [20]:
WX.loc['2017-06-01':'2017-06-01']

,Temp_F,weather_cond,pressure,wind_speed
Date_Join,,,,
2017-06-01 23:00:00-07:00,57.848,overcast clouds,1016.0,4.0
2017-06-01 22:00:00-07:00,58.244,broken clouds,1016.0,2.0
2017-06-01 21:00:00-07:00,59.252,overcast clouds,1016.0,3.0
2017-06-01 20:00:00-07:00,60.818,overcast clouds,1016.0,3.0
2017-06-01 19:00:00-07:00,63.086,overcast clouds,1015.0,3.0
2017-06-01 18:00:00-07:00,65.066,overcast clouds,1015.0,3.0
2017-06-01 17:00:00-07:00,64.652,scattered clouds,1014.0,6.0
2017-06-01 16:00:00-07:00,63.842,scattered clouds,1014.0,6.0
2017-06-01 15:00:00-07:00,63.626,scattered clouds,1014.0,5.0
2017-06-01 14:00:00-07:00,64.868,broken clouds,1014.0,5.0
2017-06-01 13:00:00-07:00,63.464,light rain,1014.0,3.0
2017-06-01 12:00:00-07:00,62.456,broken clouds,1013.0,4.0
2017-06-01 11:00:00-07:00,61.736,light rain,1013.0,3.0
2017-06-01 10:00:00-07:00,60.674,overcast clouds,1013.0,2.0
2017-06-01 09:00:00-07:00,59.270,light rain,1013.0,2.0
2017-06-01 08:00:00-07:00,58.226,moderate rain,1012.0,2.0
2017-06-01 07:00:00-07:00,57.254,mist,1013.0,1.0
2017-06-01 06:00:00-07:00,57.668,overcast clouds,1012.0,2.0
2017-06-01 05:00:00-07:00,57.470,overcast clouds,1012.0,1.0
2017-06-01 04:00:00-07:00,57.470,overcast clouds,1012.0,2.0
2017-06-01 03:00:00-07:00,57.470,light rain,1011.0,2.0
2017-06-01 02:00:00-07:00,57.452,light intensity drizzle,1012.0,3.0
2017-06-01 01:00:00-07:00,57.254,light intensity drizzle,1012.0,2.0
2017-06-01 00:00:00-07:00,57.470,light intensity drizzle,1012.0,2.0

In [8]:
temp_vis = pd.DataFrame(WX['Temp_F'])
temp_vis.groupby([temp_vis.index.month,temp_vis.index.day, temp_vis.index.hour]).mean().sample(15)

                                  Temp_F
Date_Join Date_Join Date_Join
8         19        7          62.563640
2         17        14         50.131640
7         22        6          57.948800
10        26        15         54.236900
3         23        21         44.756685
4         18        9          51.816920
7         18        5          56.378480
2         22        13         43.674761
12        19        9          37.842200
8         19        19         77.076800
          10        23         67.600760
6         11        16         68.779760
2         5         5          38.497040
7         1         0          62.898440
5         27        7          51.500741

In [9]:
fre = './Data/Bike_Counts/Fremont_Bridge.csv'
fremont = pd.read_csv(fre,parse_dates = [0],index_col='Date')

fremont.rename(columns = {'Fremont Bridge East Sidewalk' : 'EastSide',
                         'Fremont Bridge West Sidewalk':'WestSide',
                         'Date':'Date_Join'} , inplace= True)


fremont = fremont.tz_localize(pac,ambiguous = True, nonexistent = 'shift_forward')
fremont['Mean_Xing'] = fremont[['EastSide','WestSide']].mean(axis=1)

fremont.index.names=['Date_Join']

In [10]:
data = fremont.merge(WX, how = 'inner',left_on = 'Date_Join',right_on = 'Date_Join')
data['Hour'] = data.index.strftime('%H')

In [11]:
null_df = pd.DataFrame(data.isnull().sum().sort_values(ascending=False),columns=['Null_Count'])
null_df[null_df['Null_Count'] >0]
#data[data.isnull().any(axis=1)]

           Null_Count
pressure           12
EastSide            8
WestSide            8
Mean_Xing           8
Temp_F              2

In [12]:
data['pressure'].fillna(value = data['pressure'].mean(),inplace=True)
data['EastSide'].fillna(value = data['EastSide'].mean(),inplace=True)
data['WestSide'].fillna(value = data['WestSide'].mean(),inplace=True)
data['Mean_Xing'].fillna(value = data['Mean_Xing'].mean(),inplace=True)
data['Temp_F'].fillna(value = data['Temp_F'].mean(),inplace=True)

In [13]:
null_df = pd.DataFrame(data.isnull().sum().sort_values(ascending=False),columns=['Null_Count'])
null_df[null_df['Null_Count'] >0]
#data[data.isnull().any(axis=1)]

Empty DataFrame
Columns: [Null_Count]
Index: []

In [14]:
features = [
#'EastSide',
#'WestSide',
#'Mean_Xing',
'Temp_F',
'pressure',
'wind_speed',
'weather_cond_broken clouds',
'weather_cond_drizzle',
'weather_cond_few clouds',
'weather_cond_fog',
'weather_cond_haze',
'weather_cond_heavy intensity drizzle',
'weather_cond_heavy intensity rain',
'weather_cond_heavy intensity shower rain',
'weather_cond_heavy snow',
'weather_cond_light intensity drizzle',
'weather_cond_light intensity shower rain',
'weather_cond_light rain',
'weather_cond_light shower snow',
'weather_cond_light snow',
'weather_cond_mist',
'weather_cond_moderate rain',
'weather_cond_overcast clouds',
'weather_cond_proximity thunderstorm',
'weather_cond_scattered clouds',
'weather_cond_shower rain',
'weather_cond_sky is clear',
'weather_cond_smoke',
'weather_cond_snow',
'weather_cond_squalls',
'weather_cond_thunderstorm',
'weather_cond_thunderstorm with heavy rain',
'weather_cond_thunderstorm with light rain',
'weather_cond_thunderstorm with rain',
'weather_cond_very heavy rain',
'Hour'
]

In [15]:
X = data[features]
y = data['Mean_Xing']

y_baseline = [data.Mean_Xing.mean()] * len(y)


#print(X_train.shape)
#print(y_train.shape)

#print(X_test.shape)
#print(y_test.shape)
print(len(y_baseline))

45209

In [16]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge,LogisticRegression
from sklearn.model_selection import train_test_split, KFold, cross_val_score,cross_val_predict,cross_validate
from sklearn.neighbors import KNeighborsClassifier

In [17]:
lr = LinearRegression()
cv_results = cross_validate(lr,X,y,cv=5)
scores = cross_val_score(lr, X, y, cv=5,scoring='r2')
predictions = cross_val_predict(lr, X, y, cv=5)
scores

array([0.13545376, 0.13254927, 0.12844136, 0.14718073, 0.1485385 ])

In [18]:
from sklearn import preprocessing
from sklearn import utils

lab_enc = preprocessing.LabelEncoder()
y_encoded = lab_enc.fit_transform(y)

In [26]:
print(y_encoded.shape)
print(y.shape)

(45209,)
(45209,)

In [ ]:
log = LogisticRegression()
cv_results = cross_validate(log,X,y_encoded,cv=5)
scores = cross_val_score(log, X, y_encoded, cv=5,scoring='r2')
predictions = cross_val_predict(log, X, y_encoded, cv=5)
scores

C:\Users\cody.ringrissler\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\cody.ringrissler\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\cody.ringrissler\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\cody.ringrissler\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\cody.ringrissler\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\cody.ringrissler\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\cody.ringrissler\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\cody.ringrissler\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\cody.ringrissler\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\cody.ringrissler\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

In [32]:
result = {}
score = []
for i in range(1,10):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(X,y)
    score.append(model.score(X,y))
    result.update({i:model.score(X,y) })

ValueError: Unknown label type: 'continuous'